apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 8080          # The port your app is running on inside the pod
      targetPort: 8080    # The target port inside your container
      nodePort: 30000     # NodePort range: 30000-32767, can be any available port in this range
  type: NodePort